version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
  - package-ecosystem: pip
    directory: /pulumi
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
    groups:
      pulumi:
        dependency-type: "production"
      pulumi-dev:
        dependency-type: "development"
  - package-ecosystem: cargo
    directory: /app/fetcher
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
    groups:
      fetcher:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /app/bot
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
    groups:
      bot:
        patterns:
          - "*"
