name: Python CI
on:
  push:

concurrency:
  group: ghas-erfiume-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci-app:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0.0.2
    with:
      poetry-version: latest
      python-version: 3.12
      working-directory: "./app"

  python-ci-pulumi:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0.0.2
    with:
      poetry-version: latest
      python-version: 3.12
      working-directory: "./pulumi"
