[package]
name = "erfiume-fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
aws-config = "1.5.10"
aws-sdk-dynamodb = "1.55.0"
futures = "0.3.31"
lambda_runtime = "0.13.0"
openssl = { version = "0.10.66", features = [
    "vendored",
] } # Needed only for cargo lambda build
reqwest = { version = "0.12.9", features = ["json"] }
serde = "1.0.216"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
