[package]
name = "erfiume-fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
aws-config = "1.5.15"
aws-sdk-dynamodb = "1.63.0"
futures = "0.3.31"
lambda_runtime = "0.13.0"
openssl = { version = "0.10.69", features = [
    "vendored",
] } # Needed only for cargo lambda build
reqwest = { version = "0.12.12", features = ["json"] }
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
