name: Deploy Fetcher Lambda
on:
  push:
    branches:
      - main
    paths:
      - app/fetcher/**
      - .github/workflows/fetcher-deploy.yml

concurrency:
  group: ghas-erfiume-fetcher-lambda-deploy-${{ github.ref }}

jobs:
  rust-ci-fetcher:
    permissions:
      actions: read
      security-events: write
      contents: read
      id-token: write
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@rust-ci-v0.0.1
    with:
      working-directory: ./app/fetcher
      deploy-lambda: true
      aws-role: arn:aws:iam::841162699174:role/erfiume-oidc-write
      egress-policy-allowlist: >
        sts.eu-west-1.amazonaws.com:443
        lambda.eu-west-1.amazonaws.com:443
        ziglang.org:443
        pkg.machengine.org:443
