name: Deploy Lambda
on:
  push:
    branches:
      - main
    paths:
      - app/fetcher/**
      - .github/workflows/lambda-deploy.yml

concurrency:
  group: ghas-erfiume-lambda-deploy-${{ github.ref }}

jobs:
  rust-ci:
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@rust-ci-v0.1.0
    with:
      working-directory: ./app/fetcher

  lambda-deploy:
    needs: rust-ci
    name: Deploy Lambda
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./app/fetcher
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        # v4.2.0
        with:
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        # v4.0.2
        with:
          role-to-assume: arn:aws:iam::841162699174:role/erfiume-oidc-write
          aws-region: eu-west-1
          retry-max-attempts: 2
      - name: Cargo cache
        uses: swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab
        # v2.7.5
        with:
          cache-on-failure: true
          cache-all-crates: true
          workspaces: ./app/fetcher
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master
      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: cargo-lambda/cargo-lambda
          platform: linux
          arch: x86_64
      - name: Build and deploy Lambda
        run: |
          cargo lambda build --release
          cargo lambda deploy
