name: Deploy Lambda
on:
  push:
    branches:
      - main
    paths:
      - app/r/**
      - .github/workflows/lambda-deploy.yml

concurrency:
  group: ghas-erfiume-lambda-deploy-${{ github.ref }}

jobs:
    rust-ci:
      permissions:
        actions: read
        security-events: write
        contents: read
      uses: notdodo/github-actions/.github/workflows/rust-ci.yml@rust_ci
      with:
        working-directory: ./app/fetcher

  lambda-deploy:
    # name: Deploy Lambda
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./app/fetcher
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        # v4.2.0
        with:
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        # v4.0.2
        with:
          role-to-assume: arn:aws:iam::841162699174:role/erfiume-oidc-write
          aws-region: eu-west-1
          retry-max-attempts: 2
      - name: Cargo cache
        uses: swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        # v2.7.3
        with:
          cache-on-failure: true
          cache-all-crates: true
          workspaces: ./app/fetcher
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master
      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: cargo-lambda/cargo-lambda
          platform: linux
          arch: x86_64
      - name: deploy lambda
        run: |
          cargo lambda build --release
          cargo lambda deploy
