name: Rust CI
on:
  pull_request:
    paths:
      - app/fetcher/**
      - app/bot/**
      - .github/workflows/lambda-deploy.yml

concurrency:
  group: ghas-erfiume-lambda-deploy-${{ github.ref }}

jobs:
  rust-ci-fetcher:
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@rust-ci-v0.1.3
    with:
      working-directory: ./app/fetcher

  rust-ci-bot:
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@rust-ci-v0.1.3
    with:
      working-directory: ./app/bot
