name: Rust CI
on:
  pull_request:
    paths:
      - app/fetcher/**
      - app/bot/**
      - .github/workflows/rust-ci.yml

concurrency:
  group: ghas-erfiume-ci-${{ github.ref }}

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Check changed-files
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # v4.2.2
        with:
          fetch-depth: 0

      - id: changed-files
        uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366
        # v45.0.5
        with:
          files_yaml: |
            fetcher:
              - app/fetcher/**
            bot:
              - app/bot/**
            ci:
              - .github/workflows/rust-ci.yml

  rust-ci-fetcher:
    needs: changed-files
    permissions:
      actions: read
      security-events: write
      contents: read
    if: needs.changed-files.outputs.fetcher_any_changed == 'true' || needs.changed-files.outputs.ci_any_changed == 'true'
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@rust-ci-v0.0.3
    with:
      working-directory: ./app/fetcher

  rust-ci-bot:
    needs: changed-files
    permissions:
      actions: read
      security-events: write
      contents: read
    if: needs.changed-files.outputs.bot_any_changed == 'true' || needs.changed-files.outputs.ci_any_changed == 'true'
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@rust-ci-v0.0.3
    with:
      working-directory: ./app/bot
