[package]
name = "erfiume-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
aws-config = "1.5.8"
aws-sdk-dynamodb = "1.50.0"
chrono = "0.4.38"
chrono-tz = "0.10.0"
edit-distance = "2.1.3"
lambda_runtime = "0.13.0"
openssl = { version = "0.10.68", features = ["vendored"] }
serde = "1.0.210"
serde_dynamo = "4.2.14"
serde_json = "1.0.131"
teloxide = { version = "0.13.0", features = ["macros"] }
tokio = { version = "1.40.0", features = ["macros"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
