[package]
name = "erfiume-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
aws-config = "1.5.16"
aws-sdk-dynamodb = "1.64.0"
chrono = "0.4.39"
chrono-tz = "0.10.1"
edit-distance = "2.1.3"
fastrand = "2.3.0"
lambda_runtime = "0.13.0"
openssl = { version = "0.10.70", features = ["vendored"] }
serde = "1.0.217"
serde_dynamo = "4.2.14"
serde_json = "1.0.138"
teloxide = { version = "0.13.0", features = ["macros"] }
tokio = { version = "1.43.0", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
