[package]
name = "erfiume-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
aws-config = "1.5.9"
aws-sdk-dynamodb = "1.52.0"
chrono = "0.4.38"
chrono-tz = "0.10.0"
edit-distance = "2.1.3"
fastrand = "2.1.1"
lambda_runtime = "0.13.0"
openssl = { version = "0.10.68", features = ["vendored"] }
serde = "1.0.214"
serde_dynamo = "4.2.14"
serde_json = "1.0.132"
teloxide = { version = "0.13.0", features = ["macros"] }
tokio = { version = "1.41.0", features = ["macros"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
